### ISSUE TITLE
举例的代码无法运行。

### ISSUE THREAD

**Issue by zhengger** [MiYogurt/dart_server#1]
import 'package:dart_server/dart_server.dart';

main() {
  var awesome = new Awesome();
}
————————————————
main.dart:1: Warning: Interpreting this as package URI, 'package:dart_server/main.dart'.
main.dart:4:21: Error: Method not found: 'Awesome'.
  var awesome = new Awesome();

**Comment by MiYogurt** [comment]
```
dart lib/dart_server.dart
```

这只是演示代码，并不是包，readme 是由脚手架生成的，没有做修改。
